### ISSUE TITLE
Quotes unhide attachments marked as Spoiler

### ISSUE THREAD

**Issue by LilTrashPanda** [Deivedux/Quote#27]
![2019-03-05 09_28_21-window](https://user-images.githubusercontent.com/36066663/53824573-1d579980-3f29-11e9-83d9-e5060041764a.png)

When quoting a message id that includes an attachment marked as spoiler, the quoted portion will reveal the image. This issue doesn't occur with spoilered text.

**Comment by Deivedux** [comment]
While bots are able to mark their own attachments as spoilers, there does not seem like a way to do that with images in rich embeds, nor discord.py has it documented anywhere. So I can only assume that this is out of my reach, and you'd want to request this more as a Discord feature at first before I can get use it to our advantage.

**Comment by LilTrashPanda** [comment]
> While bots are able to mark their own attachments...

Got it; thanks for the info!
