### ISSUE TITLE
Prevent self-quoting

### ISSUE THREAD

**Issue by testman42** [Deivedux/Quote#30]
Is it possible to prevent bot from quoting the posts that it made?

**Comment by azusa-rs** [comment]
No matter who the author of the message is, the user can quote any, I repeat ANY message, that they want.

**Comment by Deivedux** [comment]
rude

**Comment by azusa-rs** [comment]
![no u](https://user-images.githubusercontent.com/45246543/54382573-9eeeba80-46d3-11e9-8fe6-fad7dd25bf79.png)

**Comment by testman42** [comment]
Would it not be possible to implement some per-server configuration, where Discord server owners / maintainers can decide whether they want to allow bot self-quoting or not?

**Comment by Deivedux** [comment]
It's funny that you say "self-quoting" since it still requires a user's input to quote in the first place. Quote bot by default ignores any messages sent by bots in general to avoid stuff like actual self-quoting and other loopholes.
