### ISSUE TITLE
>quotepart doesn't work at all

### ISSUE THREAD

**Issue by Finoderi** [Deivedux/Quote#31]
I tried:
 >quotepart messageID "part of the message"
>quotepart "part of the message"
>quotepart "quote part of the message"

Nothing of the above seem to work. This command either has an incorrect description or just not implemented.

**Comment by azusa-rs** [comment]
As far as I can tell, the command doesn't exist on public Quote. It might be implemented into the dev version of Quote, but listed.
Deive will get back to you later on.

**Comment by Deivedux** [comment]
The command was initially implemented because it was previously suggested, but then later on removed because of it's complex usage. I guess I simply forgot to remove it from the command list as well.
